name: build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
  
  artifact:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./artifact
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build Docker Image
        run: docker/build-push-action@v3
        with:
          context: .
          dockerfile: ./Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/app:latest 
      
      - name: Deploy to AWS ECS
        uses: aws-actions/amazon-ecs-deploy-action@v1
        with:
          accessKey: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secretKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          cluster: ${{ secrets.CLUSTER_NAME }}
          service: ${{ secrets.SERVICE_NAME }}
          imageFile: ./app 

   